name: FactionVillagers
main: main.FactionVillagers
description: FactionVillagers Minecraft Plugin
version: 0.9
author: JB & TK
depend:
  - Citizens
  - Factions
commands:
 fv:
  description: Use /fv to do stuff.